export const iphone = {
	'IMEI Number': '------',
	Brand: 'Apple iPhone',
	Model: 'IPHONE 13 GEN NVZW',
	'Blacklist Status': 'Reported lost by a T-Mobile customer',
	'Model Description': 'IPHONE 13 RED 128GB-USA',
	'IMEI Number 2': '------',
	'MEID Number': '------',
	'Serial Number': '------',
	'Activation Status': 'Device is inactive',
	'Warranty Status': 'Limited Warranty',
	'Estimated Purchase Date': '2021-10-01',
	'Purchase Country': 'United States',
	'Telephone Technical Support': 'Active',
	'Technical Support Expiration Date': '30 Dec 2021',
	technical_support_expires_in: '60 days',
	'Repairs & Service Coverage': 'Active',
	'Repairs & Service Expiration Date': '2 Nov 2021',
	'Repairs & Service Expires In': '2 days',
	'AppleCare Eligible': 'No',
	'Valid Purchase Date': 'Yes',
	Registered: 'Yes',
	'Active Apple Repair': 'No',
	'Replaced By Apple': 'No',
	'Replacement Device': 'No',
	'Demo Unit': 'No',
	'Obsolete Device': 'No',
	'Loaner Device': 'No',
	'Find My iPhone (FMI) On/Off': 'OFF',
	'Blacklist Records': '0',
	Description: 'IPHONE 13 RED 128GB-USA',
	'Purchase Date': 'October 1, 2021',
	'Device Age': '1 Month',
	Replaced: 'No',
	'Locked Carrier': 'US T-Mobile Locked Activation Policy',
	Country: 'United States',
	'SIM Lock Status': 'Locked',
	'Model Number': '------',
	Manufacturer: 'APPLE INC',
	ESN: '------',
	'Device FED Description': 'Device is valid and cleared for use',
	'SIM Type': 'Supports physical sim only',
	'Currently Active': 'NO',
	'Device FED Met': 'YES',
	SPCS: 'YES',
	'Model Brand': 'Apple',
	'ESN Status': 'Clean',
	'System Message': 'Reported lost by a T-Mobile customer',
	'Developer Code': 'DMD DEVICE IS A NOT ELIGIBLE AS PREPAY DEVICE',
	'Part Number': 'IPHONE13-NVZW',
	'Product ID': '------',
	'Device SKU': '------',
	'iCloud Lock': 'OFF',
	'Find My iPhone (FMI) Status': 'OFF',
}

export const ipad = {
	'Serial Number': '------',
	Brand: 'Apple iPad',
	Model: 'iPad (6th Generation) Wi-Fi 32GB Silver [A1893] [iPad7,5]',
	'Model Description': 'IPAD WI-FI 32GB SILVER-USA',
	'Manufacture Date': '31 Jan 2018',
	'Unit Age': '3 years, 8 months and 29 days',
	'Assembled In': 'Foxconn Zhengzhou, China',
	'Activation Status': 'Activated',
	'Warranty Status': 'Out Of Warranty',
	'Estimated Purchase Date': '17 May 2018',
	'Purchase Country': 'United States',
	'Telephone Technical Support': 'Expired',
	'Repairs & Service Coverage': 'Expired',
	'AppleCare Eligible': 'No',
	'Valid Purchase Date': 'Yes',
	Registered: 'Yes',
	'Active Apple Repair': 'No',
	'Replaced By Apple': 'No',
	'Replacement Device': 'No',
	Refurbished: 'No',
	'Demo Unit': 'No',
	'Obsolete Device': 'No',
	'Loaner Device': 'No',
	find_my_ipad: 'ON',
	Description: 'IPAD WI-FI 32GB SILVER-USA',
	'Purchase Date': 'May 17, 2018',
	'Device Age': '3 Years, 5 Months and 12 Days',
	Replaced: 'No',
	'Locked Carrier': 'Wi-Fi Device',
	Country: 'United States',
	'SIM Lock Status': 'Unlocked',
}

export const macbooks = {
	'Serial Number': '------',
	Brand: 'Apple',
	Model: 'RFB',
	'Manufacture Date': '30 Mar 2016',
	'Unit Age': '5 years, 6 months and 30 days',
	'Assembled In': 'Foxconn Chengdu, China',
	'Activation Status': 'Activated',
	'Warranty Status': 'Out Of Warranty',
	'Estimated Purchase Date': '2 May 2016',
	'Telephone Technical Support': 'Expired',
	'Repairs & Service Coverage': 'Expired',
	'AppleCare Eligible': 'No',
	'Valid Purchase Date': 'Yes',
	Registered: 'Yes',
	'Active Apple Repair': 'No',
	'Replaced By Apple': 'No',
	Refurbished: 'No',
	'Obsolete Device': 'No',
	'Loaner Device': 'No',
	Description: 'MacBook Air (13-inch, Early 2015)',
	'Purchase Date': '2016-05-02',
	'Device Age': '5 Years, 5 Months and 27 Days',
	Replaced: 'No',
	'Device Status': 'Refurbished',
	'Locked Carrier': 'Wi-Fi Device',
	Country: 'United States',
	'SIM Lock Status': 'Unlocked',
	Configuration: 'RFB MBAIR 13.3/1.6GHZ/8GB/128GB',
	Warranty: 'Expired',
	'Find My iPhone (FMI) Status': 'OFF',
}

export const airpods = {
	'Serial Number': '------',
	Brand: 'Apple AirPods',
	Model: 'AirPods Generation 2 / AirPods2,1 / AirPods with Wireless Charging Case',
	'Manufacture Date': '17 Jun 2020',
	'Unit Age': '1 year, 4 months and 12 days',
	'Activation Status': 'Not Activated',
	'Warranty Status': 'Out Of Warranty',
	'Estimated Purchase Date': '3 Sep 2020',
	'Telephone Technical Support': 'N/A',
	'Repairs & Service Coverage': 'N/A',
	'AppleCare Eligible': 'No',
	'Valid Purchase Date': 'No',
	Registered: 'No',
	'Active Apple Repair': 'No',
	'Replaced By Apple': 'No',
	'Obsolete Device': 'No',
	'Loaner Device': 'No',
	Description: 'AIRPODS WITH WIRELESS CHARGING CASE-AME',
	'Purchase Date': 'September 3, 2020',
	'Device Age': '1 Year, 1 Month and 26 Days',
	Replaced: 'No',
	'Locked Carrier': 'Wi-Fi Device',
	Country: 'United States',
	'SIM Lock Status': 'Unlocked',
}

export const watch = {
	'Serial Number': '------',
	Brand: 'Apple Watch',
	Model: 'Apple Watch Series 4 16GB Space Gray Aluminium 44MM Wi-Fi [A1978] [Watch4,2]',
	'Model Description': 'APPLE WATCH S4 44 SG AL BLK SP GPS-USA',
	'Model Config': 'WATCH SERIES 4  SPACE GRAY 44MM',
	'Part Number': '------',
	'Part Number Country': 'USA/Canada',
	'Part Type': 'Retail Unit',
	'Manufacture Date': '12 Sep 2018',
	'Unit Age': '3 years, 1 month and 17 days',
	'Assembled In': 'Fremont California, USA',
	'Activation Status': 'Activated',
	'Warranty Status': 'Out Of Warranty',
	'Estimated Purchase Date': '23 Sep 2018',
	'Purchase Country': 'United States',
	'Telephone Technical Support': 'Expired',
	'Repairs & Service Coverage': 'Expired',
	'AppleCare Eligible': 'No',
	'Valid Purchase Date': 'Yes',
	Registered: 'Yes',
	'Active Apple Repair': 'No',
	'Replaced By Apple': 'No',
	'Replacement Device': 'No',
	Refurbished: 'No',
	'Demo Unit': 'No',
	'Obsolete Device': 'No',
	'Loaner Device': 'No',
	'Find My Watch Status': 'OFF',
	Description: 'APPLE WATCH S4 44 SG AL BLK SP GPS-USA',
	'Purchase Date': 'September 23, 2018',
	'Device Age': '3 Years, 1 Month and 6 Days',
	Replaced: 'No',
	'Locked Carrier': 'Wi-Fi Device',
	Country: 'United States',
	'SIM Lock Status': 'Unlocked',
}

export const samsung = {
	'Full Name': 'Samsung Galaxy S7 32GB Sprint Black Onyx',
	'Model Info': 'HHP-Smart Phone-Pocket type&Water Resist',
	'Search Term': '------',
	'IMEI Number': '------',
	'Serial Number': '------',
	'DO Number': '------',
	'Model Number': '------',
	Model: 'SM-G930P',
	'Model Description': 'Galaxy S7 32GB (Sprint)',
	'Warranty Status': 'Warranty Expired',
	'Production Date': '08-04-2016',
	'Warranty Until': '08-04-2017',
	Manufacturer: 'Samsung Electronics Huizhou (China)',
	Carrier: 'Usa Sprint',
	'Sold-By': 'United States / 13 April 2016',
}

export const coupon_codes = [{ label: '80off', value: 0.8, type: 'percentage' }]

export const payment_method = { wallet: 'Wallet', paypal: 'PayPal', creditCard: 'Credit/Debit Card' }
